### ISSUE TITLE
WPML 3.7.1 breaks plugin: Class 'WPML_Auto_Loader' not found

### ISSUE THREAD

**Issue by florianfink** [OnTheGoSystems/WPML-MU-Domain-Mapping#1]
Hello,

I'm using this plugin with Wordpress 4.8. After the update to WPML 3.7.1, the plugin stops working with this error message:

`[Sat Jun 17 17:33:27 2017] [warn] [client x.x.x.x] mod_fcgid: stderr: PHP Fatal error:  Class 'WPML_Auto_Loader' not found in /var/www/wp-content/plugins/wpml-mu-domain-mapping/plugin.php on line 20`

Would be great to have a fix for this as soon as possible, as it breaks some parts of the website.

**Comment by strategio** [comment]
Hello @florianfink and thanks for reporting the issue.

I prepared a branch https://github.com/OnTheGoSystems/WPML-MU-Domain-Mapping/tree/wpmlbridge-94 which should fix the issue.

Could you test it and let me know it solves the problem on your side?

Note: Just download the ZIP and install it on your site.

**Comment by florianfink** [comment]
hi strategio,

thanks for the fast fix. This seems to work fine so far!

**Comment by strategio** [comment]
Hi @florianfink,

We've updated the plugin to version 1.1.0 with the fix.

I will close this issue, but feel free to open a new one if needed.

Thanks again :)
