### ISSUE TITLE
Readme entirely missing

### ISSUE THREAD

**Issue by elosha** [OnTheGoSystems/WPML-MU-Domain-Mapping#6]
Hi, could you please supply a proper readme file?
– What is this plugin supposed to do?
– Dependencies on other plugins, including version
– Compatibility with Wordpress versions
– Basic usage hints
– Will this add the long missing cross-domain functionality?

Thanks.
A paying WPML corporate user

**Comment by dgwatkins** [comment]
Hi Elosha

It's just a "glue" plugin, let me explain. 

The functionality is actually provided by one of these 2 plugins:
http://wordpress.org/extend/plugins/wordpress-mu-domain-mapping/
https://premium.wpmudev.org/project/domain-mapping/

When using one of the above plugins with WPML, a few things don't work properly.
Here is where this "glue" plugin is needed, to fill in the gaps.

You can read the full documentation here:
https://wpml.org/documentation/support/multisite-support/multilingual-site-network-with-domain-mapping/

If you have any issues, please open a support ticket in our support forum:
https://wpml.org/forums/forum/english-support/

**Comment by elosha** [comment]
Thanks, ok, but maybe add this as Readme file. Helps understanding much quicker and without asking.

**Comment by dgwatkins** [comment]
I added a note to our project manager to improve this, thanks for the suggestion.
